export default {
  calling: 'Calling',
  loadingZoom: 'Loading Zoom...',
  startACall: "Let's start a call!",
  makeACall: 'Please make a call from your ONSCREEN app.',
  enterANameForDevice: 'Please enter a name for this device!',
  setUpYourNetwork: "Let's set up your network.",
  connectYourAccount: " Let's connect your account.",
  connectTheseNetwork: "Please connect to\none of these networks:",
  holdQRCode: ' Hold up the QR code from the ONSCREEN app to the camera.',
  needTheApp: 'Need the app? Go to app.onscreeninc.com.',
  connectingTo: 'Connecting to {{networkName}}...',
  networkConnected: 'Network connected! Verifying your account...',
  startingUp: 'Starting up...',
  connectTheWebcam: "Please connect the\nwebcam to continue.",
  alreadyConnectedPlugItBack:
    "If it's already connected, please unplug it and plug it back in.",
  couldNotConnectWiFi: 'We could not connect to WiFi, please try again.',
  networkName: 'Network Name: {{name}}',
  providedPassword: 'Provided Password: {{password}}',
  upcomingEvents: 'Upcoming Events',
  importantCheckTheOnScreen:
    'IMPORTANT: Please check the ONSCREEN mobile app for tips on improving your wifi connection.',
  cannotReachTheInternet:
    'Cannot reach the Internet, please check your connection.',
  isCalling: 'is Calling...',
  connecting: 'Connecting...',
  autoAnsweringInSeconds: 'Auto-answering in {{seconds}} seconds...',
  seconds: 'seconds.',
  sayOnScreenHangup: "Say 'onscreen hangup' to cancel the call.",
  sayOnScreenAnswer: "Say 'onscreen answer' to answer immediately.",
  autoAnsweringNow: 'Auto-answering now...',
  pleaseWaitLeavingCall: 'Please wait, leaving call...',
  localVideo: 'Local Video: {{stat}}',
  localAudio: 'Local Audio: {{stat}}',
  remoteVideo: 'Remote Video: {{stat}}',
  remoteAudio: 'Remote Audio: {{stat}}',
  pleaseRecord: 'Please record a {{seconds}} second message.',
  thankYouForUpdate: 'Thank you for your update!',
  sending: 'Sending...',
  allDone: 'All done!',
  errorWithMessage: 'Error: {{message}}',
  poorConnection: 'Poor connection',
  howAreYouFeeling: 'How are you feeling?'
};
