export default {
    calling: 'Klicanje',
    loadingZoom: 'Nalaganje Zoom ...',
    startACall: "Začnimo klic!",
    makeACall: 'Prosimo, pokličite iz aplikacije ONSCREEN.',
    enterANameForDevice: 'Prosimo, vnesite ime za to napravo!',
    setUpYourNetwork: "Nastavimo vaše omrežje.",
    connectYourAccount: "Povežimo vaš račun.",
    connectTheseNetwork: "Povežite se z\nenim od teh omrežij:",
    holdQRCode: ' Približajte kodo QR iz aplikacije ONSCREEN do kamere.',
    needTheApp: 'Potrebujete aplikacijo? Pojdite na app.onscreeninc.com.',
    connectingTo: 'Povezovanje z {{networkName}}...',
    networkConnected: 'Omrežje povezano! Preverjanje vašega računa ...',
    launchUp: 'Zaganjanje...',
    connectTheWebcam: "Za nadaljevanje povežite\nspletno kamero.",
    alreadyConnectedPlugItBack:
        "Če je že povezan, ga izključite in ponovno vključite.",
    couldNotConnectWiFi: 'Nismo se mogli povezati z WiFi omrežjem, poskusite znova.',
    networkName: 'Ime omrežja: {{name}}',
    providedPassword: 'Ponujeno geslo: {{password}}',
    upcomingEvents: 'Prihajajoči dogodki',
    importantCheckTheOnScreen:
     'POMEMBNO: Preverite mobilno aplikacijo ONSCREEN za nasvete o izboljšanju vaše povezave Wi-Fi.',
    cannotReachTheInternet:
     'Ne morem doseči interneta, preverite povezavo.',
    isCalling: 'kliče ...',
    connecting: 'Povezovanje ...',
    autoAnsweringInSeconds: 'Samodejni odgovor v {{seconds}} sekundah ...',
    seconds: 'sekund.',
    sayOnScreenHangup: "Izgovorite 'onscreen hangup', da prekličete klic.",
    sayOnScreenAnswer: "Izgovorite 'onscreen answer', da odgovorite takoj.",
    autoAnsweringNow: 'Samodejni odgovor zdaj ...',
    pleaseWaitLeavingCall: 'Prosim počakajte, zapuščam klic ...',
    localVideo: 'Lokalni video: {{stat}}',
    localAudio: 'Lokalni zvok: {{stat}}',
    remoteVideo: 'Oddaljeni video: {{stat}}',
    remoteAudio: 'Oddaljeni zvok: {{stat}}',
    pleaseRecord: 'Prosimo, posnemite {{seconds}} sekundno sporočilo.',
    thankYouForUpdate: 'Hvala za posodobitev!',
    sendingconnecting: 'Pošiljanje ...',
    allDone: 'Vse končano!',
    errorWithMessage: 'Napaka: {{message}}',
    poorConnection: 'Slaba povezava',
    howAreYouFeeling: 'Kako se počutiš?'
};
